[float]
[[modules-node-xpack]]
== [xpack]#X-Pack 节点设置#

//This content is referenced from the elastic/elasticsearch/docs/reference/modules/node.asciidoc

如果安装了 {xpack}，那么有一个额外的节点类型：

<<ml-node,机器学习节点>>::

将 `xpack.ml.enabled` 和 `node.ml` 设置为 `true` 的节点，安装 {xpack} 时的默认行为。如果您想使用 {xpackml} 功能，集群中必须至少有一个 {ml} 节点。更多有关 {xpackml} 功能的信息，参见 {xpack-ref}/xpack-ml.html[Machine Learning in the Elastic Stack]。

IMPORTANT: 除非安装了 {xpack}，否则不要设置使用 `node.ml` 设置。否则，节点无法启动。

如果安装了xpack，则节点默认是候选主节点、数据节点、摄取节点和 {ml} 节点。随着集群的增长，尤其是有大量 {ml} 作业时，考虑将专用候选主节点与专用数据节点和专用 {ml} 节点分开。

要在安装 {xpack} 时创建专用候选主节点，请设置：

[source,yaml]
-------------------
node.master: true <1>
node.data: false <2>
node.ingest: false <3>
node.ml: false <4>
xpack.ml.enabled: true <5>
-------------------
<1> 默认启用 `node.master` 角色。
<2> 禁用 `node.data` 角色（默认启用）。
<3> 禁用 `node.ingest` 角色（默认启用）。
<4> 禁用 `node.ml` 角色（在 {xpack} 中默认启用）。
<5> 在 {xpack} 中默认启用 `xpack.ml.enabled` 设置。

要在安装 {xpack} 时创建专用数据节点，请设置：

[source,yaml]
-------------------
node.master: false <1>
node.data: true <2>
node.ingest: false <3>
node.ml: false <4>
-------------------
<1> 禁用 `node.master` 角色（默认启用）。
<2> 默认启用 `node.data`  角色。
<3> 禁用 `node.ingest` 角色（默认启用）。
<4> 禁用 `node.ml` 角色（在 {xpack} 中默认启用）。

要在安装 {xpack} 时创建专用摄入节点，请设置：

[source,yaml]
-------------------
node.master: false <1>
node.data: false <2>
node.ingest: true <3>
cluster.remote.connect: false <4>
node.ml: false <5>
-------------------
<1> 禁用 `node.master` 角色（默认启用）。
<2> 禁用 `node.data` 角色（默认启用）。
<3> 默认启用 `node.ingest` 角色。
<4> 禁用跨集群搜索（默认启用）。
<5> 禁用 `node.ml` 角色（在 {xpack} 中默认启用）。

要在安装 {xpack} 时创建专用协调节点，请设置：

[source,yaml]
-------------------
node.master: false <1>
node.data: false <2>
node.ingest: false <3>
cluster.remote.connect: false <4>
node.ml: false <5>
-------------------
<1> 禁用 `node.master` 角色（默认启用）。
<2> 禁用 `node.data` 角色（默认启用）。
<3> 禁用 `node.ingest` 角色（默认启用）。
<4> 禁用跨集群搜索（默认启用）。
<5> 禁用 `node.ml` 角色（在 {xpack} 中默认启用）。

[float]
[[ml-node]]
=== [xpack]#机器学习节点#

{xpackml} 功能提供了 {ml} 节点，用来运行任务和处理 {ml} API 请求。 如果 `xpack.ml.enabled` 设置为 true 并且 `node.ml` 设置为 `false`，那么该节点可服务于 API 请求但不能运行任务。

如果想在集群中使用 {xpackml} 功能，必须在全部候选主节点上启用 {ml}。如果没有安装 {xpack}，不要使用这些设置。

更多关于这些设置的信息，请看 <<ml-settings, 机器学习设置>>。

要创建一个专用 {ml} 节点，请设置：

[source,yaml]
-------------------
node.master: false <1>
node.data: false <2>
node.ingest: false <3>
cluster.remote.connect: false <4>
node.ml: true <5>
xpack.ml.enabled: true <6>
-------------------
<1> 禁用 `node.master` 角色（默认启用）。
<2> 禁用 `node.data` 角色（默认启用）。
<3> 禁用 `node.ingest` 角色（默认启用）。
<4> 禁用跨集群搜索（默认启用）。
<5> {xpack} 中默认启用 `node.ml` 角色。
<6> {xpack} 中默认启用 `xpack.ml.enabled` 设置。
